export const USER_DATA_SAVE = 'USER_DATA_SAVE';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const GET_FEATURED_PRODUCT = 'GET_FEATURED_PRODUCT';
export const GET_LATEST_PRODUCT = 'GET_LATEST_PRODUCT';
